require("edipratech.plugins-setup")
require("edipratech.core.options")
require("edipratech.core.keymaps")
require("edipratech.core.colorscheme")
require("edipratech.plugins.comment")
require("edipratech.plugins.lualine")
require("edipratech.plugins.telescope")
require("edipratech.plugins.nvim-cmp")
require("edipratech.plugins.lsp.mason")
-- require("edipratech.plugins.nvim-tree")
