-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

--require("hyprland-alt.lua")

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "highres",
    position = "auto",
    scale    = 1.0,
})

hl.monitor({
    output   = "eDP-1",
    mode     = "highres",
    position = "auto",
    scale    = 1.33,
})

hl.monitor({
    output   = "DP-1",
    mode     = "3440x1440@240",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080",
    position = "-1080x660",
    scale    = 1.000,
    transform = 3,
})

hl.monitor({
    output   = "DP-3",
    mode     = "2560x1080",
    position = "0x-1080",
    scale    = 1.00,
    transform = 2,
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch

-- exec-once = waybar & hyprpaper & firefox

--exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1




-- for GTK3 apps


-- for GTK4 apps

--exec-once = waybar




-- Auto start Apps


--exec-once = vivaldi

-- Hyprshade


-- screen timeout

-- Source a file (multi-file configs)

-- source = ~/.config/hypr/myColors.conf

-- Some default env vars.

hl.env("XCURSOR_SIZE", 14)

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})

hl.device({
    name = "logitech-m570",
    sensitivity = -0.75,
})

hl.config({
    cursor = {
        no_hardware_cursors = 1,
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 2,
        gaps_out = 0,
        border_size = 2,
        layout = "dwindle",
        col = {
            active_border = "rgb(0076ed)",
            inactive_border = "rgba(f7509350)",
        },
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 10,
        --    blur = yes
        --    blur_size = 3
        --    blur_passes = 1
        --    blur_new_optimizations = on
        --    drop_shadow = yes
        --    shadow_range = 4
        --    shadow_render_power = 3
        --    col.shadow = rgba(1a1a1aee)
    },
})

hl.config({
    animations = {
        enabled = false,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        preserve_split = true,
        -- you probably want this
    },
})

hl.config({
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        --workspace_swipe = off
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

hl.device({
    name = "epic-mouse-v1",
})

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "ALT"

local altMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

-- bind = $mainMod, $altMod, exec, alacritty

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd("wlogout"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.exec_cmd("thunar"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5 --effect-vignette 0.5:0.5 --ring-color bb00cc --key-hl-color 880033 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 --fade-in 0.2"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "SPACE", hl.dsp.window.float())

-- hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind("ALT + D", hl.dsp.exec_cmd(
    "qs ipc call shell toggle omarchy.menu '{\"menu\":\"root\"}'"
))

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd("terminator"))

--bind = $mainMod, P, pseudo, # dwindle

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "W", hl.dsp.exec_cmd("waybar"))

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", { direction = "l" })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", { direction = "d" })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", { direction = "u" })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", { direction = "r" })

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind("SUPER+ALT" .. " + " .. "J", hl.dsp.group.next())

hl.bind("SUPER+ALT" .. " + " .. "K", hl.dsp.group.next({ forward = false }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- Move Workspace

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + P", hl.dsp.movecurrentworkspacetomonitor("r"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + O", hl.dsp.movecurrentworkspacetomonitor("l"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + U", hl.dsp.movecurrentworkspacetomonitor("u"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + I", hl.dsp.movecurrentworkspacetomonitor("d"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- # Workspace for laptop monitor

-- workspace=1,monitor:eDP-1

-- workspace=2,monitor:eDP-1

-- workspace=3,monitor:eDP-1

-- workspace=4,monitor:eDP-1

-- workspace=5,monitor:eDP-1

-- workspace=6,monitor:eDP-1

-- workspace=7,monitor:eDP-1

-- workspace=8,monitor:eDP-1

-- workspace=9,monitor:eDP-1

-- workspace=10,monitor:eDP-1

-- # Workspace for external monitor

-- workspace=11,monitor:DP-3

-- workspace=12,monitor:DP-3

-- workspace=13,monitor:DP-3

-- workspace=14,monitor:DP-3

-- workspace=15,monitor:DP-3

-- workspace=16,monitor:DP-3

-- workspace=17,monitor:DP-3

-- workspace=18,monitor:DP-3

-- workspace=19,monitor:DP-3

-- workspace=110,monitor:DP-3

-- bind = $mainMod, 1, exec, hyprsome workspace 1

-- bind = $mainMod, 2, exec, hyprsome workspace 2

-- bind = $mainMod, 3, exec, hyprsome workspace 3

-- bind = $mainMod, 4, exec, hyprsome workspace 4

-- bind = $mainMod, 5, exec, hyprsome workspace 5

-- bind = $mainMod, 6, exec, hyprsome workspace 6

-- bind = $mainMod, 7, exec, hyprsome workspace 7

-- bind = $mainMod, 8, exec, hyprsome workspace 8

-- bind = $mainMod, 9, exec, hyprsome workspace 9

-- bind = $mainMod, 0, exec, hyprsome workspace 10

-- bind = $mainMod CTRL, 1, exec, hyprsome workspace 11

-- bind = $mainMod CTRL, 2, exec, hyprsome workspace 12

-- bind = $mainMod CTRL, 3, exec, hyprsome workspace 13

-- bind = $mainMod CTRL, 4, exec, hyprsome workspace 14

-- bind = $mainMod CTRL, 5, exec, hyprsome workspace 15

-- bind = $mainMod CTRL, 6, exec, hyprsome workspace 16

-- bind = $mainMod CTRL, 7, exec, hyprsome workspace 17

-- bind = $mainMod CTRL, 8, exec, hyprsome workspace 18

-- bind = $mainMod CTRL, 9, exec, hyprsome workspace 19

-- bind = $mainMod CTRL, 0, exec, hyprsome workspace 110

-- bind = $mainMod SHIFT, 1, exec, hyprsome move 1

-- bind = $mainMod SHIFT, 2, exec, hyprsome move 2

-- bind = $mainMod SHIFT, 3, exec, hyprsome move 3

-- bind = $mainMod SHIFT, 4, exec, hyprsome move 4

-- bind = $mainMod SHIFT, 5, exec, hyprsome move 5

-- bind = $mainMod SHIFT, 6, exec, hyprsome move 6

-- bind = $mainMod SHIFT, 7, exec, hyprsome move 7

-- bind = $mainMod SHIFT, 8, exec, hyprsome move 8

-- bind = $mainMod SHIFT, 9, exec, hyprsome move 9

-- bind = $mainMod SHIFT, 0, exec, hyprsome move 10

-- bind = $mainMod CTRL SHIFT, 1, exec, hyprsome move 11

-- bind = $mainMod CTRL SHIFT, 2, exec, hyprsome move 12

-- bind = $mainMod CTRL SHIFT, 3, exec, hyprsome move 13

-- bind = $mainMod CTRL SHIFT, 4, exec, hyprsome move 14

-- bind = $mainMod CTRL SHIFT, 5, exec, hyprsome move 15

-- bind = $mainMod CTRL SHIFT, 6, exec, hyprsome move 16

-- bind = $mainMod CTRL SHIFT, 7, exec, hyprsome move 17

-- bind = $mainMod CTRL SHIFT, 8, exec, hyprsome move 18

-- bind = $mainMod CTRL SHIFT, 9, exec, hyprsome move 19

-- bind = $mainMod CTRL SHIFT, 0, exec, hyprsome move 110

-- Rezise Windows

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + L", hl.dsp.resizeactive("10 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + H", hl.dsp.resizeactive("-10 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CRTL + J", hl.dsp.resizeactive("0 -10"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + CTRL + K", hl.dsp.resizeactive("0 10"))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "F1", hl.dsp.focus({ workspace = 11 }))

hl.bind(mainMod .. " + " .. "F2", hl.dsp.focus({ workspace = 12 }))

hl.bind(mainMod .. " + " .. "F3", hl.dsp.focus({ workspace = 13 }))

hl.bind(mainMod .. " + " .. "F4", hl.dsp.focus({ workspace = 14 }))

hl.bind(mainMod .. " + " .. "F5", hl.dsp.focus({ workspace = 15 }))

hl.bind(mainMod .. " + " .. "F6", hl.dsp.focus({ workspace = 16 }))

hl.bind(mainMod .. " + " .. "F7", hl.dsp.focus({ workspace = 17 }))

hl.bind(mainMod .. " + " .. "F8", hl.dsp.focus({ workspace = 18 }))

hl.bind(mainMod .. " + " .. "F9", hl.dsp.focus({ workspace = 19 }))

hl.bind(mainMod .. " + " .. "F10", hl.dsp.focus({ workspace = 110 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({workspace = 1}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({workspace = 2}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({workspace = 3}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({workspace = 4}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({workspace = 5}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({workspace = 6}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({workspace = 7}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({workspace = 8}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({workspace = 9}))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({workspace = 10}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 1, hl.dsp.window.move({workspace = 11}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 2, hl.dsp.window.move({workspace = 12}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 3, hl.dsp.window.move({workspace = 13}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 4, hl.dsp.window.move({workspace = 14}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 5, hl.dsp.window.move({workspace = 15}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 6, hl.dsp.window.move({workspace = 16}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 7, hl.dsp.window.move({workspace = 17}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 8, hl.dsp.window.move({workspace = 18}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 9, hl.dsp.window.move({workspace = 19}))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. 0, hl.dsp.window.move({workspace = 110}))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + " .. "t", hl.dsp.group.toggle())

-- Volume

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))

hl.bind("print", hl.dsp.exec_cmd("grim -g $(slurp) /home/edipratech/Pictures/Screenshots/$(date +'%s_grim.png')"))

-- bind = $mainMod,XF86MonBrightnessUp,exec, $HOME/.config/hypr/scripts/nightmode.sh toggle

hl.bind(mainMod .. " + " .. "XF86MonBrightnessDown", hl.dsp.exec_cmd("hyprshade on blue-light-filter"))

hl.bind(mainMod .. " + " .. "XF86MonBrightnessUp", hl.dsp.exec_cmd("hyprshade off"))

-- built in monitor

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "M", hl.dsp.exec_cmd("~/dotfiles/hypr/scripts/lid.sh"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("lxqt-policykit-agent")
    hl.exec_cmd("hypridle >> ~/hypridle.log")
    hl.exec_cmd("brave")
    hl.exec_cmd("hyprpaper")
    --hl.exec_cmd("qs")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme Adwaita")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
    hl.exec_cmd("pkill waybar; waybar")
    hl.exec_cmd("hyprshade auto")
end)

-- Omarchy Quattro shortcut adapter for the user's Hyprland Lua config.
-- Omarchy's SUPER modifier is intentionally replaced with LEFT ALT.
-- Add these binds to your existing hyprland.lua after resolving any collisions.

hl.bind(altMod .. " + " .. "SPACE", hl.dsp.exec_cmd("omarchy-shell shell toggle omarchy.menu '{\"menu\":\"root\"}'"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("omarchy-shell shell toggle omarchy.clipboard"))
hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("omarchy-shell shell toggle omarchy.notifications"))

-- Workspace navigation remains with your existing ALT+number bindings.
-- Do not duplicate your existing ALT bindings; merge these selectively.