{ inputs, config, pkgs, ... }:
let unstable = import <unstable>
  { config = {allowUnfree = true; }; };
in
{
  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
environment.systemPackages = with pkgs; [
    amdgpu_top
    audacity
    auto-cpufreq
    azahar
    blueman
    brave
    brightnessctl
    btop
    cargo
    unstable.cisco-packet-tracer_9
    #davinci-resolve
    dfu-programmer
    dfu-util
    discord
    distrobox
    docker
    dxvk
    ethtool
    fastfetch 
    feh
    filezilla
    firefox
    fprintd
    freerdp
    freetype
    freetube
    fwupd
    fuzzel
    fzf
    gcc
    gh
    gimp
    git
    glibc
    go
    gnome-font-viewer
    gnome-network-displays
    gnumake
    gparted
    gpg-tui
    grim
    gtk3
    gvfs
    home-manager
    htop
    unstable.hypridle
    unstable.hyprlock
    unstable.hyprland
    unstable.hyprshade
    kdePackages.sddm 
    #kicad
    krita
    libreoffice-fresh
    libsecret
    # libsForQt5.kdenlive
    libvirt
    lsd
    lutris
    lunar-client #minecraft
    lxappearance
    lxqt.lxqt-policykit
    macchanger
    #mariadb
    meson
    # miraclecast
    moonlight-qt
<<<<<<< HEAD
    #mullvad-browser
    ninja
=======
    mouseless
>>>>>>> c0b82242016554b63183d849829df95eab7e8ff8
    netcat
    networkmanagerapplet
    unstable.neovim
    nfs-utils
    ninja
    niri
    nitrogen
    nodejs_20
    npins
    oh-my-zsh
    openvpn
    orca-slicer
    OVMFFull
    p7zip
    pamixer
    parsec-bin
    pavucontrol
    pcsx2
    picom
    pipewire
    polybar
    ppsspp
    prismlauncher
    pulseaudio
    python315
    python313Packages.pip
    python313Packages.west
    qemu_kvm
    qmk
    retroarch
    rofi
    #ruby_4_0
    #rubyPackages_4_0.rails
    rustup
    slurp
    spotify
    sqlite
    steam
    swaybg
    swayidle
    swaylock-effects
    swtpm
    tailscale
    teamspeak6-client
    terminator
    thunderbird
    tldr
    tmux
    tor
    udiskie
    udisks
    unrar
    unzip
    usbutils
    vial
    virt-manager
    virtiofsd
    vivaldi
    #vmware-workstation
    unstable.vscode
    waybar
    wget
    wine
    winetricks
    wine-staging
    wireplumber
    wireshark
    wlsunset
    wofi
    xfce.thunar
    xfce.thunar-volman
    #xfwm4
    xwayland
    zed-editor
    #zoom-us
    zsh
    pkgsCross.avr.buildPackages.gcc
    gcc-arm-embedded
  ];
}
