{ inputs, config, pkgs, ... }:
let unstable = import <unstable>
  { config = {allowUnfree = true; }; };
in
{
  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
environment.systemPackages = with pkgs; [
    amdgpu_top
    audacity
    auto-cpufreq
    azahar
    blueman
    brave
    brightnessctl
    btop
    cargo
    #unstable.cisco-packet-tracer_9
    #davinci-resolve
    dfu-programmer
    dfu-util
    discord
    distrobox
    docker
    dxvk
    ethtool
    fastfetch 
    fdupes
    feh
    filezilla
    firefox
    fprintd
    freerdp
    freetype
    freetube
    fwupd
    fuzzel
    fzf
    gcc
    gh
    gimp
    git
    glibc
    gnome-font-viewer
    gnome-network-displays
    gnumake
    go
    gparted
    gpg-tui
    grayjay
    grim
    gtk3
    gvfs
    home-manager
    htop
    unstable.hypridle
    unstable.hyprlock
    unstable.hyprland
    unstable.hyprshade
    unstable.hyprpaper
    imagemagick
    kdePackages.sddm 
    #kicad
    krita
    libreoffice-fresh
    libsecret
    # libsForQt5.kdenlive
    libvirt
    lsd
    lxappearance
    lxqt.lxqt-policykit
    macchanger
    #mariadb
    meson
    # miraclecast
    moonlight-qt
    mousepad
    netcat
    networkmanagerapplet
    unstable.neovim
    nfs-utils
    ninja
    nitrogen
    nodejs_26
    npins
    oh-my-zsh
    openvpn
    orca-slicer
    OVMFFull
    p7zip
    pamixer
    parsec-bin
    pavucontrol
    pcsx2
    picom
    pipewire
    polybar
    ppsspp
    prismlauncher
    pulseaudio
    python315
    python313Packages.pip
    python313Packages.west
    qemu_kvm
    unstable.quickshell
    retroarch
    rofi
    #ruby_4_0
    #rubyPackages_4_0.rails
    rustup
    slurp
    spotify
    sqlite
    steam
    swtpm
    tailscale
    teamspeak6-client
    terminator
    thunar
    thunar-volman
    thunderbird
    tldr
    tmux
    tor
    udiskie
    udisks
    unrar
    unzip
    usbutils
    vial
    virt-manager
    virtiofsd
    virtualenv
    #vmware-workstation
    unstable.vscode
    waybar
    wget
    wine
    winetricks
    wine-staging
    wireplumber
    wireshark
    wlsunset
    wofi
    #xfwm4
    xwayland
    zed-editor
    #zoom-us
    zsh
    pkgsCross.avr.buildPackages.gcc
    gcc-arm-embedded
  ];
}
